steps:
  # Mengambil file dari GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/zulfahmidev/capstone_api.git']

  # Menyiapkan lingkungan Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-docker-image:${_ID}', 'capstone_api']
    env:
      - 'ID=$(date +%Y%m%d%H%M%S)'

  # Menyimpan Docker image ke GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gcr.io/$PROJECT_ID/my-docker-image:${_ID}', 'gs://my-bucket/my-docker-image-${_ID}']

images:
  - 'gcr.io/$PROJECT_ID/my-docker-image:${_ID}'
