steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >
        vmlist=$(gcloud compute instances list --format='value(name)' --filter="labels.${_VM_LABEL_KEY}:${_VM_LABEL_VALUE} AND status:RUNNING") && for vm in $vmlist; do gcloud compute ssh cloudbuild@$vm --zone $(gcloud compute instances list --format='value(zone)' --filter="name='$vm'") --quiet -- 'gsutil cp gs://private-capstone/startuptest.sh . && sudo chmod +x startuptest.sh && sudo sh startuptest.sh '; done
    entrypoint: bash
 
