"""empty message

Revision ID: 5fb3cf067613
Revises: c4989d165bcb
Create Date: 2023-05-30 13:02:12.038947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fb3cf067613'
down_revision = 'c4989d165bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_constraint('fields_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'forms', ['form_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_constraint('options_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'fields', ['field_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_constraint('responses_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('responses_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('responses_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('responses_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'options', ['option_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('form_id')
        batch_op.drop_column('field_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('form_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('responses_ibfk_4', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('responses_ibfk_3', 'options', ['option_id'], ['id'])
        batch_op.create_foreign_key('responses_ibfk_1', 'fields', ['field_id'], ['id'])
        batch_op.create_foreign_key('responses_ibfk_2', 'forms', ['form_id'], ['id'])

    with op.batch_alter_table('options', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('options_ibfk_1', 'fields', ['field_id'], ['id'])

    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fields_ibfk_1', 'forms', ['form_id'], ['id'])

    # ### end Alembic commands ###
