"""empty message

Revision ID: 682a9398d37d
Revises: b23e63801fd9
Create Date: 2023-05-19 21:44:11.723322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682a9398d37d'
down_revision = 'b23e63801fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reset_password', schema=None) as batch_op:
        batch_op.drop_index('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reset_password', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    # ### end Alembic commands ###
