"""empty message

Revision ID: 8b9fd1212d38
Revises: 5fb3cf067613
Create Date: 2023-06-02 21:35:43.125169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9fd1212d38'
down_revision = '5fb3cf067613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('field_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fields', ['field_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'forms', ['form_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('field_id')
        batch_op.drop_column('form_id')

    # ### end Alembic commands ###
