"""empty message

Revision ID: fc072ab628c6
Revises: a12120e3478c
Create Date: 2023-05-17 19:24:16.319979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc072ab628c6'
down_revision = 'a12120e3478c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_identifier', sa.Text(), nullable=False),
    sa.Column('destroy_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_log')
    # ### end Alembic commands ###
